Feature: math operations
  Scenario: add two digits
    When I add 1 and 2
    Then the result should equal 3

    Scenario: eth_getBlockByNumber without params mainnet
        When I send a request with following params
            | Method  | POST         | #BASE_URL# |
            | Headers | Content-Type | application/json          |
            | Json    | jsonrpc      | 2.0                       |
            | Json    | id           | 1                         |
            | Json    | method       | eth_getBlockByNumber      |
            | Json    | params[0]    | latest                    |
            | Json    | params[1]    | false                     |
        Then I should get json response with following properties:
            | Path                    | Value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | jsonrpc                 | 2.0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | result.author           | 0x0000000000000000000000000000000000000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | result.difficulty       | 0x64                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
            | result.extraData        | 0x                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | result.gasLimit         | 0x989680                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
            | result.gasUsed          | 0x0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | result.hash             | 0xd95d0157cf1976630524ff3dc8d06f88670c7e913ee1b32cdc747792eb95e9b9                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | result.logsBloom        | 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 |
            | result.miner            | 0x0000000000000000000000000000000000000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | result.number           | 0x0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | result.parentHash       | 0x0000000000000000000000000000000000000000000000000000000000000000                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | result.receiptsRoot     | 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | result.sha3Uncles       | 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | result.signature        | 0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000                                                                                                                                                                                                                                                                                                                                                                                               |
            | result.size             | 0x216                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | result.stateRoot        | 0xd24141462904e0137d827b846bb691d9806d0c0396ffa05ca209003c162afdaa                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | result.totalDifficulty  | %StringContaining(0x64)%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
            | result.timestamp        | 0x54c98c81                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
            | result.transactionsRoot | 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
            | id                      | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
        And I should receive a response with the status "200"
        And the header "Content-Type" should be "application/json"
